### ISSUE TITLE
Reproducibility errors

### ISSUE THREAD

**Issue by scottgigante** [xzhoulab/DRComparison#1]
Hi,

It's not clear to me how to run this code. After discovering and installing all of the dependencies, I have run into these errors:

For ZIFA:
```
/var/spool/slurmd/job43468578/slurm_script: line 34: cd: ../algorithm/ZIFA: No such file or directory
python: can't open file 'block_ZIFA_commd.py': [Errno 2] No such file or directory
```

For scScope:
```
/gpfs/ysm/project/sag86/conda_envs/python/lib/python3.7/site-packages/scanpy/api/__init__.py:6: FutureWarning: 

In a future version of Scanpy, `scanpy.api` will be removed.
Simply use `import scanpy as sc` and `import scanpy.external as sce` instead.

  FutureWarning
Traceback (most recent call last):
  File "call_scScope.py", line 27, in <module>
    counts_drop = pd.read_csv(args.counts_file, header=0, index_col=0)
  File "/gpfs/ysm/project/sag86/conda_envs/python/lib/python3.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/gpfs/ysm/project/sag86/conda_envs/python/lib/python3.7/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/gpfs/ysm/project/sag86/conda_envs/python/lib/python3.7/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/gpfs/ysm/project/sag86/conda_envs/python/lib/python3.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/gpfs/ysm/project/sag86/conda_envs/python/lib/python3.7/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'../data/sce_Baron_scScope.csv' does not exist
```

and DCA simply does not produce any output.

**Comment by scottgigante** [comment]
Could you please provide a start to end pipeline (including scripts to install the pipeline) that runs the experiment and produces the figures / tables shown in your paper? Thanks very much!

**Comment by sqsun** [comment]
Hi Scott,

Thanks for letting me know about these bugs. For ZIFA, I have updated the code, it works now; For DCA, ZIFA, and scScope, you have to convert the .rds data to .txt/.csv format. I have uploaded an example code (in data folder) that you can do the transformation. Thanks!
